version: '3'
services:
  node:
    image: andreired/simple-node
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
     - postgres
    restart: always
    environment:
      - PORT=${PORT}
      - TZ=${TIME_ZONE}
    networks:
      - andreired-net
    volumes:
      - ./logs:/usr/app/logs
      - ./src:/usr/app/src
  postgres:
    image: andreired/postgres
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - andreired-net
    volumes:
      - ./database/data:/var/lib/postgresql/data
networks:
    andreired-net:
      driver: bridge